DROP TABLE IF EXISTS CUSTOMER, ORDER, DELIVERY, PIZZA, PIZZA_INGREDIENT, ORDER_STATUS, PIZZA_ORDER, PIZZA_RECIPE;

CREATE TABLE CUSTOMER(
    Customer_ID NUMERIC (3),
    Name VARCHAR (40),
    Phone CHAR (12),
    Address VARCHAR (40)
) ENGINE InnoDB;

CREATE TABLE ORDER(
    Order_ID NUMERIC (3),
    Customer_ID NUMERIC (3),
    Feedback_Score NUMERIC (3),
    Comment CHAR (50),
    Date DATE,
    Order_Time VARCHAR (7), 
    Total_Price VARCHAR (100)
) ENGINE InnoDB;

CREATE TABLE DELIVERY(
    Employee_ID NUMERIC (3),
    Customer_ID NUMERIC (3),
    Trip_Distance VARCHAR (4),
    Time_Delivered VARCHAR (7)
) ENGINE InnoDB;

CREATE TABLE PIZZA(
    Pizza_ID NUMERIC (3),
    Size CHAR (1),
    Quantity_of_Pizzas NUMERIC (100),
    Pizza_Type CHAR (9)
) ENGINE InnoDB;

CREATE TABLE PIZZA_INGREDIENT(
    Ingredient_ID NUMERIC (3),
    Pizza_ID NUMERIC (3),
    Ingredient_Type VARCHAR (100),
    Ingredient_Quantity NUMERIC (100)
) ENGINE InnoDB;

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_Customer_ID_pk PRIMARY KEY (Customer_ID);
ALTER TABLE ORDER ADD CONSTRAINT ORDER_Order_ID_pk PRIMARY KEY (Order_ID);
ALTER TABLE DELIVERY ADD CONSTRAINT DELIVERY_Employee_ID_pk PRIMARY KEY (Employee_ID);
ALTER TABLE PIZZA ADD CONSTRAINT PIZZA_Pizza_ID_pk PRIMARY KEY (Pizza_ID);
ALTER TABLE PIZZA_INGREDIENT ADD CONSTRAINT PIZZA_INGREDIENT_Ingredient_ID_pk PRIMARY KEY (Ingredient_ID);

ALTER TABLE ORDER ADD CONSTRAINT ORDER_Customer_ID_fk FOREIGN KEY (Customer_ID);
ALTER TABLE DELIVERY ADD CONSTRAINT DELIVERY_Customer_ID_fk FOREIGN KEY (Customer_ID);
ALTER TABLE PIZZA_INGREDIENT ADD CONSTRAINT PIZZA_INGREDIENT_Pizza_ID_fk FOREIGN KEY (Pizza_ID);
ALTER TABLE PIZZA ADD CONSTRAINT PIZZA_Ingredient_ID_fk FOREIGN KEY (Ingredient_ID);

INSERT INTO CUSTOMER VALUES
(123, 'Jack', '415 658-9932', '6223 Bateman St.');
INSERT INTO ORDER VALUES
(333, 123, 5, 'Very Good', '1997-7-17', '12:30pm', '$12.50');
INSERT INTO DELIVERY VALUES
(666, 123, '12KM', '20MIN');
INSERT INTO PIZZA VALUES
(777, 'L', 2, 'Hawaiian');
INSERT INTO PIZZA_INGREDIENT VALUES
(000, 777, 'Cheese', '25')

CREATE TABLE ORDER_STATUS (
    Order_ID NUMERIC (3)
) ENGINE InnoDB;

CREATE TABLE PIZZA_ORDER (
    Pizza_ID NUMERIC (3),
    Order_ID NUMERIC (3)
) ENGINE InnoDB;

CREATE TABLE PIZZA_RECIPE (
    Pizza_ID NUMERIC (3),
    Ingredient_ID NUMERIC (3)
) ENGINE InnoDB;

ALTER TABLE PIZZA_RECIPE ADD CONSTRAINT PIZZA_RECIPE_Pizza_ID_fk FOREIGN KEY (Pizza_ID);
ALTER TABLE PIZZA_RECIPE ADD CONSTRAINT PIZZA_RECIPE_Ingredient_ID_fk FOREIGN KEY (Ingredient_ID);

ALTER TABLE PIZZA_ORDER ADD CONSTRAINT PIZZA_ORDER_Pizza_ID_fk FOREIGN KEY (Pizza_ID);
ALTER TABLE PIZZA_ORDER ADD CONSTRAINT PIZZA_ORDER_Order_ID_fk FOREIGN KEY (Order_ID);

ALTER TABLE ORDER_STATUS ADD CONSTRAINT ORDER_STATUS_Order_ID_fk FOREIGN KEY (Order_ID);

INSERT INTO ORDER_STATUS
(333);
INSERT INTO PIZZA_ORDER
(777, 333);
INSERT INTO PIZZA_RECIPE
(777, 000); 